version: '3.8'

services:
  db:
    image: mongo:7
    container_name: life-rpg-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: liferpg
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    command: mongod --replSet rs0

volumes:
  mongodata:
